import assert from 'node:assert/strict'
import test from 'node:test'
import { AltiumLibraryBatchExporter } from '../../src/core/altium/AltiumLibraryBatchExporter.mjs'
import { AltiumPcbLibExporter } from '../../src/core/altium/AltiumPcbLibExporter.mjs'
import { AltiumSchLibExporter } from '../../src/core/altium/AltiumSchLibExporter.mjs'
import { OleCompoundDocument } from '../../src/core/ole/OleCompoundDocument.mjs'
import { PcbLibStreamExtractor } from '../../src/core/altium/PcbLibStreamExtractor.mjs'
import { SourceBundleExporter } from '../../src/core/altium/SourceBundleExporter.mjs'
import { SourceComponentBundleNormalizer } from '../../src/core/altium/SourceComponentBundleNormalizer.mjs'
import { SourceComponentClient } from '../../src/core/altium/SourceComponentClient.mjs'

/**
 * Builds a deterministic fake provider component response.
 * @param {string} [id] Component identifier.
 * @returns {object}
 */
function createRawComponent(id = 'source-widget') {
    return {
        id,
        name: 'Source Widget',
        data: {
            metadata: {
                description: 'Synthetic source component',
                package: 'FAKE_WIDGET_0603'
            },
            symbol: {
                name: 'FAKE_WIDGET_SYMBOL',
                pins: [
                    { name: 'A', number: '1' },
                    { name: 'B', number: '2' }
                ],
                primitives: [{ type: 'rectangle', x: 0, y: 0 }]
            },
            footprint: {
                name: 'FAKE_WIDGET_0603',
                pads: [
                    { name: '1', x: -20, y: 0 },
                    { name: '2', x: 20, y: 0 }
                ],
                tracks: [{ layer: 'TopOverlay', width: 4 }]
            },
            models: [
                {
                    name: 'fake-widget.step',
                    format: 'step',
                    text: 'ISO-10303-21;\nEND-ISO-10303-21;'
                }
            ]
        }
    }
}

/**
 * Converts one byte view into an exact ArrayBuffer slice.
 * @param {Uint8Array} bytes Bytes to convert.
 * @returns {ArrayBuffer}
 */
function toArrayBuffer(bytes) {
    return bytes.buffer.slice(
        bytes.byteOffset,
        bytes.byteOffset + bytes.byteLength
    )
}

/**
 * Opens a generated OLE document as a stream map.
 * @param {Uint8Array} bytes Generated bytes.
 * @returns {Map<string, Uint8Array>}
 */
function openStreams(bytes) {
    const document = OleCompoundDocument.fromArrayBuffer(toArrayBuffer(bytes))
    return new Map(
        document.listStreams().map((name) => [name, document.getStream(name)])
    )
}

test('SourceComponentBundleNormalizer creates deterministic bundles', () => {
    const bundle =
        SourceComponentBundleNormalizer.normalize(createRawComponent())

    assert.equal(bundle.id, 'source-widget')
    assert.equal(bundle.name, 'Source Widget')
    assert.equal(bundle.symbol.name, 'FAKE_WIDGET_SYMBOL')
    assert.equal(bundle.footprint.name, 'FAKE_WIDGET_0603')
    assert.equal(bundle.models[0].name, 'fake-widget.step')
    assert.equal(bundle.models[0].format, 'step')
    assert.equal(bundle.metadata.description, 'Synthetic source component')
    assert.deepEqual(bundle.diagnostics, [])
})

test('SourceBundleExporter emits source JSON and model assets', () => {
    const bundle =
        SourceComponentBundleNormalizer.normalize(createRawComponent())
    const exportResult = SourceBundleExporter.export(bundle)
    const paths = exportResult.entries.map((entry) => entry.path)

    assert.deepEqual(paths, [
        'manifest.json',
        'models/fake-widget.step',
        'source/source.json'
    ])
    assert.equal(exportResult.manifest.component.id, 'source-widget')
    assert.match(
        new TextDecoder().decode(exportResult.entries[2].bytes),
        /FAKE_WIDGET_SYMBOL/
    )
})

test('SourceComponentClient uses injected fetch with retry', async () => {
    const calls = []
    const fetcher = async (url) => {
        calls.push(String(url))
        if (calls.length === 1) {
            return {
                ok: false,
                status: 503,
                text: async () => 'busy'
            }
        }
        return {
            ok: true,
            status: 200,
            json: async () => ({ results: [createRawComponent('found-a')] })
        }
    }
    const client = new SourceComponentClient({
        fetcher,
        baseUrl: 'https://components.invalid',
        retryCount: 1
    })

    const results = await client.searchComponents('widget 0603')

    assert.equal(results[0].id, 'found-a')
    assert.equal(calls.length, 2)
    assert.match(calls[0], /q=widget\+0603/)
})

test('SourceComponentClient requires an injected fetcher', async () => {
    const client = new SourceComponentClient()

    await assert.rejects(
        () => client.searchComponents('widget'),
        /fetcher is required/
    )
})

test('AltiumSchLibExporter writes readable schematic library streams', () => {
    const bundle =
        SourceComponentBundleNormalizer.normalize(createRawComponent())
    const streams = openStreams(AltiumSchLibExporter.export([bundle]))

    assert.deepEqual([...streams.keys()].sort(), [
        'Components/FAKE_WIDGET_SYMBOL/Data',
        'Library/Data'
    ])
    assert.match(
        new TextDecoder().decode(streams.get('Library/Data')),
        /FAKE_WIDGET_SYMBOL/
    )
    assert.match(
        new TextDecoder().decode(
            streams.get('Components/FAKE_WIDGET_SYMBOL/Data')
        ),
        /PinCount=2/
    )
})

test('AltiumPcbLibExporter writes readable footprint library and model streams', () => {
    const bundle =
        SourceComponentBundleNormalizer.normalize(createRawComponent())
    const streams = openStreams(AltiumPcbLibExporter.export([bundle]))
    const extraction = PcbLibStreamExtractor.extractFromStreams(streams)

    assert.equal(extraction.footprints[0].name, 'FAKE_WIDGET_0603')
    assert.equal(extraction.footprints[0].declaredPrimitiveCount, 0)
    assert.equal(extraction.embeddedModels.models[0].name, 'fake-widget.step')
    assert.match(
        extraction.embeddedModels.models[0].payloadText,
        /ISO-10303-21/
    )
})

test('AltiumLibraryBatchExporter supports merged output, append skip, and progress', async () => {
    const progress = []
    const fetchedIds = []
    const client = {
        /**
         * Fetches a fake bundle for one source id.
         * @param {string} id Component id.
         * @returns {Promise<object>}
         */
        async fetchComponentBundle(id) {
            fetchedIds.push(id)
            return SourceComponentBundleNormalizer.normalize(
                createRawComponent(id)
            )
        }
    }
    const exporter = new AltiumLibraryBatchExporter({ client })
    const result = await exporter.exportIds(['part-a', 'part-b'], {
        appendManifest: { completedIds: ['part-b'] },
        includeSourceBundle: true,
        includeSchLib: true,
        includePcbLib: true,
        merged: true,
        onProgress: (event) => progress.push(event)
    })

    assert.deepEqual(fetchedIds, ['part-a'])
    assert.deepEqual(result.checkpoint.completedIds, ['part-b', 'part-a'])
    assert(
        result.entries.some((entry) => entry.path === 'part-a/manifest.json')
    )
    assert(
        result.entries.some((entry) => entry.path === 'merged/library.SchLib')
    )
    assert(
        result.entries.some((entry) => entry.path === 'merged/library.PcbLib')
    )
    assert.deepEqual(
        progress.map((event) => event.status),
        ['exported', 'skipped']
    )
})
