// SPDX-FileCopyrightText: 2026 André Fiedler
//
// SPDX-License-Identifier: GPL-3.0-or-later

export { BinaryReader } from './core/BinaryReader.mjs'
export { OleCompoundDocument } from './core/ole/OleCompoundDocument.mjs'
export { OleConstants } from './core/ole/OleConstants.mjs'
export { OleDirectoryEntry } from './core/ole/OleDirectoryEntry.mjs'
export { AltiumParser } from './core/altium/AltiumParser.mjs'
export { AltiumLayoutParser } from './core/altium/AltiumLayoutParser.mjs'
export { AsciiRecordParser } from './core/altium/AsciiRecordParser.mjs'
export { ParserUtils } from './core/altium/ParserUtils.mjs'
export { NormalizedModelSchema } from './core/altium/NormalizedModelSchema.mjs'
export { CircuitJsonModelSchema } from './core/circuit-json/CircuitJsonModelSchema.mjs'
export { CircuitJsonModelAdapter } from './core/circuit-json/CircuitJsonModelAdapter.mjs'
export { PcbBinaryPrimitiveParser } from './core/altium/PcbBinaryPrimitiveParser.mjs'
export { PcbBoardRegionSemanticsParser } from './core/altium/PcbBoardRegionSemanticsParser.mjs'
export { PcbComponentPrimitiveIndexer } from './core/altium/PcbComponentPrimitiveIndexer.mjs'
export { PcbEmbeddedFontExtractor } from './core/altium/PcbEmbeddedFontExtractor.mjs'
export { PcbEmbeddedModelExtractor } from './core/altium/PcbEmbeddedModelExtractor.mjs'
export { PcbFontMetricsParser } from './core/altium/PcbFontMetricsParser.mjs'
export { PcbLayerIdCodec } from './core/altium/PcbLayerIdCodec.mjs'
export { PcbLibModelParser } from './core/altium/PcbLibModelParser.mjs'
export { PcbLibStreamExtractor } from './core/altium/PcbLibStreamExtractor.mjs'
export { PcbModelParser } from './core/altium/PcbModelParser.mjs'
export { PcbOutlineRasterizer } from './core/altium/PcbOutlineRasterizer.mjs'
export { PcbOutlineRecovery } from './core/altium/PcbOutlineRecovery.mjs'
export { PcbPadStackParser } from './core/altium/PcbPadStackParser.mjs'
export { PcbRawRecordRegistry } from './core/altium/PcbRawRecordRegistry.mjs'
export { PcbRuleParser } from './core/altium/PcbRuleParser.mjs'
export { PcbStreamExtractor } from './core/altium/PcbStreamExtractor.mjs'
export { PcbViaStackParser } from './core/altium/PcbViaStackParser.mjs'
export { PrintableTextDecoder } from './core/altium/PrintableTextDecoder.mjs'
export { PrjPcbModelParser } from './core/altium/PrjPcbModelParser.mjs'
export { SchematicMultipartOwnerMatcher } from './core/altium/SchematicMultipartOwnerMatcher.mjs'
export { SchematicStandaloneCalloutNormalizer } from './core/altium/SchematicStandaloneCalloutNormalizer.mjs'
