// SPDX-FileCopyrightText: 2026 André Fiedler
//
// SPDX-License-Identifier: GPL-3.0-or-later

export { BinaryReader, BinaryReaderCursor } from './core/BinaryReader.mjs'
export { OleCompoundDocument } from './core/ole/OleCompoundDocument.mjs'
export { OleConstants } from './core/ole/OleConstants.mjs'
export { OleDirectoryEntry } from './core/ole/OleDirectoryEntry.mjs'
export { OleCompoundDocumentWriter } from './core/ole/OleCompoundDocumentWriter.mjs'
export { AltiumLibraryBatchExporter } from './core/altium/AltiumLibraryBatchExporter.mjs'
export { AltiumLibraryRecordBuilder } from './core/altium/AltiumLibraryRecordBuilder.mjs'
export { AltiumPcbLibExporter } from './core/altium/AltiumPcbLibExporter.mjs'
export { AltiumSchLibExporter } from './core/altium/AltiumSchLibExporter.mjs'
export { SelectedPartAltiumExportAdapter } from './core/altium/SelectedPartAltiumExportAdapter.mjs'
export { AltiumUnits } from './core/altium/AltiumUnits.mjs'
export { SourceBundleExporter } from './core/altium/SourceBundleExporter.mjs'
export { SourceComponentBundleNormalizer } from './core/altium/SourceComponentBundleNormalizer.mjs'
export { SourceComponentClient } from './core/altium/SourceComponentClient.mjs'
export { AltiumParser } from './core/altium/AltiumParser.mjs'
export { AltiumSchematicArcAngleNormalizer } from './core/altium/AltiumSchematicArcAngleNormalizer.mjs'
export { AltiumSchematicFreeGraphicStrokeNormalizer } from './core/altium/AltiumSchematicFreeGraphicStrokeNormalizer.mjs'
export { AltiumSchematicHiddenDesignatorResolver } from './core/altium/AltiumSchematicHiddenDesignatorResolver.mjs'
export { AltiumSchematicPackedImageResolver } from './core/altium/AltiumSchematicPackedImageResolver.mjs'
export { AltiumSchematicSheetBoundsNormalizer } from './core/altium/AltiumSchematicSheetBoundsNormalizer.mjs'
export { AltiumLayoutParser } from './core/altium/AltiumLayoutParser.mjs'
export { AsciiRecordParser } from './core/altium/AsciiRecordParser.mjs'
export { HostCapabilityDiagnosticsBuilder } from './core/altium/HostCapabilityDiagnosticsBuilder.mjs'
export { IntLibModelParser } from './core/altium/IntLibModelParser.mjs'
export { IntLibStreamExtractor } from './core/altium/IntLibStreamExtractor.mjs'
export { EmbeddedAssetReportBuilder } from './core/altium/EmbeddedAssetReportBuilder.mjs'
export { EmbeddedFileInventoryBuilder } from './core/altium/EmbeddedFileInventoryBuilder.mjs'
export { FixtureCoverageMatrixBuilder } from './core/altium/FixtureCoverageMatrixBuilder.mjs'
export { GeometryBoundsReportBuilder } from './core/altium/GeometryBoundsReportBuilder.mjs'
export {
    ParameterCollection,
    ParameterValue
} from './core/altium/ParameterCollection.mjs'
export {
    AltiumFileError,
    AltiumParseError,
    AltiumCorruptFileError,
    AltiumUnsupportedFeatureError
} from './core/altium/ParserErrors.mjs'
export { CiArtifactBundleBuilder } from './core/altium/CiArtifactBundleBuilder.mjs'
export { ContractGateReportBuilder } from './core/altium/ContractGateReportBuilder.mjs'
export { DraftsmanBoardViewMetadataBuilder } from './core/altium/DraftsmanBoardViewMetadataBuilder.mjs'
export { DraftsmanDigestParser } from './core/altium/DraftsmanDigestParser.mjs'
export { LibraryRenderManifestBuilder } from './core/altium/LibraryRenderManifestBuilder.mjs'
export { LibraryCatalogArtifactBuilder } from './core/altium/LibraryCatalogArtifactBuilder.mjs'
export { LibraryCompatibilityReportBuilder } from './core/altium/LibraryCompatibilityReportBuilder.mjs'
export { LibraryDiffReportBuilder } from './core/altium/LibraryDiffReportBuilder.mjs'
export { LibraryInspectionReportBuilder } from './core/altium/LibraryInspectionReportBuilder.mjs'
export { LibraryQaReportBuilder } from './core/altium/LibraryQaReportBuilder.mjs'
export { LibrarySearchIndex } from './core/altium/LibrarySearchIndex.mjs'
export { NativeStreamInventoryBuilder } from './core/altium/NativeStreamInventoryBuilder.mjs'
export { ParserUtils } from './core/altium/ParserUtils.mjs'
export { ParameterRecordInventoryBuilder } from './core/altium/ParameterRecordInventoryBuilder.mjs'
export { ParserCompatibilityFuzzer } from './core/altium/ParserCompatibilityFuzzer.mjs'
export { ParserDiagnosticNormalizer } from './core/altium/ParserDiagnosticNormalizer.mjs'
export { ParserFieldCoverageReportBuilder } from './core/altium/ParserFieldCoverageReportBuilder.mjs'
export { ParserValueVerificationReportBuilder } from './core/altium/ParserValueVerificationReportBuilder.mjs'
export { NormalizedModelSchema } from './core/altium/NormalizedModelSchema.mjs'
export { ProjectDesignBundleBuilder } from './core/altium/ProjectDesignBundleBuilder.mjs'
export { ProjectDocumentGraphBuilder } from './core/altium/ProjectDocumentGraphBuilder.mjs'
export { ProjectHierarchyReportBuilder } from './core/altium/ProjectHierarchyReportBuilder.mjs'
export { ProjectAnnotationParser } from './core/altium/ProjectAnnotationParser.mjs'
export { ProjectNetlistExporter } from './core/altium/ProjectNetlistExporter.mjs'
export { ProjectVariantViewBuilder } from './core/altium/ProjectVariantViewBuilder.mjs'
export { CircuitJsonModelSchema } from './core/circuit-json/CircuitJsonModelSchema.mjs'
export { CircuitJsonModelAdapter } from './core/circuit-json/CircuitJsonModelAdapter.mjs'
export { PcbBinaryPrimitiveParser } from './core/altium/PcbBinaryPrimitiveParser.mjs'
export { PcbBomProfileBuilder } from './core/altium/PcbBomProfileBuilder.mjs'
export { PcbBoardRegionSemanticsParser } from './core/altium/PcbBoardRegionSemanticsParser.mjs'
export { PcbComponentKindPolicy } from './core/altium/PcbComponentKindPolicy.mjs'
export { PcbComponentPrimitiveIndexer } from './core/altium/PcbComponentPrimitiveIndexer.mjs'
export { PcbCustomPadShapeParser } from './core/altium/PcbCustomPadShapeParser.mjs'
export { PcbDimensionParser } from './core/altium/PcbDimensionParser.mjs'
export { PcbDimensionReportBuilder } from './core/altium/PcbDimensionReportBuilder.mjs'
export { PcbEmbeddedFontExtractor } from './core/altium/PcbEmbeddedFontExtractor.mjs'
export { PcbEmbeddedModelExtractor } from './core/altium/PcbEmbeddedModelExtractor.mjs'
export { PcbExtendedPrimitiveInformationParser } from './core/altium/PcbExtendedPrimitiveInformationParser.mjs'
export { PcbFabricationReadinessReportBuilder } from './core/altium/PcbFabricationReadinessReportBuilder.mjs'
export { PcbFontMetricsParser } from './core/altium/PcbFontMetricsParser.mjs'
export { PcbLayerIdCodec } from './core/altium/PcbLayerIdCodec.mjs'
export { PcbLayerGroups } from './core/altium/PcbLayerGroups.mjs'
export { PcbLayerStackFidelityReportBuilder } from './core/altium/PcbLayerStackFidelityReportBuilder.mjs'
export { PcbLayerStackInterchangeParser } from './core/altium/PcbLayerStackInterchangeParser.mjs'
export { PcbLayerStackQueryHelper } from './core/altium/PcbLayerStackQueryHelper.mjs'
export { PcbLibModelParser } from './core/altium/PcbLibModelParser.mjs'
export { PcbLibParityReportBuilder } from './core/altium/PcbLibParityReportBuilder.mjs'
export { PcbLibStreamExtractor } from './core/altium/PcbLibStreamExtractor.mjs'
export { PcbMechanicalLayerPairParser } from './core/altium/PcbMechanicalLayerPairParser.mjs'
export { PcbModelParser } from './core/altium/PcbModelParser.mjs'
export { PcbOutlineRasterizer } from './core/altium/PcbOutlineRasterizer.mjs'
export { PcbOutlineRecovery } from './core/altium/PcbOutlineRecovery.mjs'
export { PcbOwnershipGraphBuilder } from './core/altium/PcbOwnershipGraphBuilder.mjs'
export { PcbPadStackParser } from './core/altium/PcbPadStackParser.mjs'
export { PcbPlacedFootprintManifestBuilder } from './core/altium/PcbPlacedFootprintManifestBuilder.mjs'
export { PcbPickPlacePositionResolver } from './core/altium/PcbPickPlacePositionResolver.mjs'
export { PcbPolygonRecordParser } from './core/altium/PcbPolygonRecordParser.mjs'
export { PcbPrimitiveFieldOffsetReportBuilder } from './core/altium/PcbPrimitiveFieldOffsetReportBuilder.mjs'
export { PcbRawRecordRegistry } from './core/altium/PcbRawRecordRegistry.mjs'
export { PcbReviewMetadataBuilder } from './core/altium/PcbReviewMetadataBuilder.mjs'
export { PcbReviewPolygonRealizationBuilder } from './core/altium/PcbReviewPolygonRealizationBuilder.mjs'
export { PcbClassReportBuilder } from './core/altium/PcbClassReportBuilder.mjs'
export { PcbInspectionReportBuilder } from './core/altium/PcbInspectionReportBuilder.mjs'
export { PcbNetMembershipReportBuilder } from './core/altium/PcbNetMembershipReportBuilder.mjs'
export { PcbRouteAnalysisBuilder } from './core/altium/PcbRouteAnalysisBuilder.mjs'
export { PcbRuleImpactReportBuilder } from './core/altium/PcbRuleImpactReportBuilder.mjs'
export { PcbRuleParser } from './core/altium/PcbRuleParser.mjs'
export { PcbSidecarRecordParser } from './core/altium/PcbSidecarRecordParser.mjs'
export { PcbSpecialStringResolver } from './core/altium/PcbSpecialStringResolver.mjs'
export { PcbStatisticsBuilder } from './core/altium/PcbStatisticsBuilder.mjs'
export { PcbStreamExtractor } from './core/altium/PcbStreamExtractor.mjs'
export { PcbUnionParser } from './core/altium/PcbUnionParser.mjs'
export { PcbViaStackParser } from './core/altium/PcbViaStackParser.mjs'
export { PcbViaStructureParser } from './core/altium/PcbViaStructureParser.mjs'
export { PrintableTextDecoder } from './core/altium/PrintableTextDecoder.mjs'
export { PrjPcbModelParser } from './core/altium/PrjPcbModelParser.mjs'
export { PrjScrModelParser } from './core/altium/PrjScrModelParser.mjs'
export { ProjectBomPnpReconciliationBuilder } from './core/altium/ProjectBomPnpReconciliationBuilder.mjs'
export { RawDataPreservationReportBuilder } from './core/altium/RawDataPreservationReportBuilder.mjs'
export { SchLibModelParser } from './core/altium/SchLibModelParser.mjs'
export { SchLibStreamExtractor } from './core/altium/SchLibStreamExtractor.mjs'
export { SchematicMultipartOwnerMatcher } from './core/altium/SchematicMultipartOwnerMatcher.mjs'
export { SchematicCrossSheetConnectorParser } from './core/altium/SchematicCrossSheetConnectorParser.mjs'
export { SchematicCodeSymbolParser } from './core/altium/SchematicCodeSymbolParser.mjs'
export { SchematicConnectivityQaBuilder } from './core/altium/SchematicConnectivityQaBuilder.mjs'
export { SchematicHarnessParser } from './core/altium/SchematicHarnessParser.mjs'
export { SchematicImplementationParser } from './core/altium/SchematicImplementationParser.mjs'
export { SchematicImageDiagnosticsBuilder } from './core/altium/SchematicImageDiagnosticsBuilder.mjs'
export { SchematicOwnershipGraphParser } from './core/altium/SchematicOwnershipGraphParser.mjs'
export { SchematicProjectParameterResolver } from './core/altium/SchematicProjectParameterResolver.mjs'
export { SchematicQaReportBuilder } from './core/altium/SchematicQaReportBuilder.mjs'
export { SchematicRecordStreamParser } from './core/altium/SchematicRecordStreamParser.mjs'
export { SchematicRecordTypeRegistry } from './core/altium/SchematicRecordTypeRegistry.mjs'
export { SchematicRepeatedChannelParser } from './core/altium/SchematicRepeatedChannelParser.mjs'
export { SchematicTemplateParser } from './core/altium/SchematicTemplateParser.mjs'
export { UnsupportedFeatureReportBuilder } from './core/altium/UnsupportedFeatureReportBuilder.mjs'
export { SchematicTextRunParser } from './core/altium/SchematicTextRunParser.mjs'
export { SchematicStandaloneCalloutNormalizer } from './core/altium/SchematicStandaloneCalloutNormalizer.mjs'
export { SvgModelCrossLinkValidator } from './core/altium/SvgModelCrossLinkValidator.mjs'
